name: test_project
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  graphql_flutter: ^5.2.0-beta.4
  freezed_annotation: ^2.2.0
  graphql_codegen: ^0.13.2
  json_annotation: ^4.8.1
  flutter_hooks: ^0.18.6
  built_value: ^8.2.0
  built_collection: ^5.0.0
  fluttertoast: ^8.2.2
  build_runner: ^2.3.3
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  very_good_analysis: ^3.1.0

flutter:
  assets:
    - assets/images/
    - assets/json/
    - assets/images/category/
    - assets/images/nav-bar/
    - assets/images/physical_consultation/

  generate: true
  uses-material-design: true
